apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl
  template:
    metadata:
      labels:
        app: fl
    spec:
      containers:
      - name: fl
        image: fl
